import { Geist, Geist_Mono,Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import TopBar from "./sections/TopBar";
import Footer from "./sections/Footer";
import ContactUs from "./sections/ContactUs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
        <TopBar />

        <Navbar />
        </div>
        {children}
        <ContactUs />
        <Footer />
      </body>
    </html>
  );
}
